# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 657e9fc460c9fccbb96a3e9b39f0ad6a73eb9edbfbfd1471ba5da18203b1d09fe904edd95cf694d51962ae1486c787616c26dcea015cb0af4b93af245fb19e8a

test:
  secret_key_base: 0ee0189f0e05b2a220bf28da59b9c869f8eca899189dad8e9a31c2c98457b98791019e400ff2731185e3e1254982cd3522c546f9fb2b60b55e234a7d802fbfe4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
